before_script:
  - rm -rf /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit
  - mkdir -p /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit
  - mv * /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit
  - cd /root/go/src/gitlab.jiagouyun.com/cloudcare-tools/datakit
  - export GO111MODULE=off

variables:
  PROJECT: "datakit"

stages:
  - deploy

build:
  stage: deploy
  only:
    - /^release(\/|-)?.*$/
    - CI # for test
    - dev
    - /^pre(\/|-)?.*$/
    - branch-to-debug-gitlab-CI
  script:
    - make test
  tags:
    - cloudcare-tools

buildRTM:
  stage: deploy
  only:
    - /\d+\.\d+\.\d+-\w+-\d+-prod/

  script:
    - go build -v -o ./image/kodo main.go
    - V=(${CI_COMMIT_REF_NAME//[\.-]/ })
    - VDIR=${V[0]}.${V[1]}.${V[2]}
    - REPO=dataflux/$VDIR
    - TAG=${PROJECT}-${V[3]}-${V[4]}
    - docker build -t $REPO:$TAG ./image/
    - docker tag $REPO:$TAG pubrepo.jiagouyun.com/$REPO:$TAG
    - docker push pubrepo.jiagouyun.com/$REPO:$TAG
  tags:
    - cloudcare

buildRTMPrev:
  stage: deploy
  only:
    - /\d+\.\d+\.\d+\.\d+-\w+-prev/
  script:
    - go build -v -o ./image/kodo main.go
    - V=(${CI_COMMIT_REF_NAME//[\.-]/ })
    - VDIR=${V[0]}.${V[1]}.${V[2]}.${V[3]}
    - REPO=dataflux-prev/$VDIR
    - TAG=${PROJECT}-${V[4]}
    - docker build -t $REPO:$TAG ./image/
    - docker tag $REPO:$TAG pubrepo.jiagouyun.com/$REPO:$TAG
    - docker push pubrepo.jiagouyun.com/$REPO:$TAG
  tags:
    - cloudcare


