annotations:
  catalog.cattle.io/certified: partner # Enables the "partner" badge in the UI for easier identification
  catalog.cattle.io/release-name: datakit # Your chart's name in kebab-case, this is used for deployment
  catalog.cattle.io/display-name: DataKit # The chart's name you want displayed in the UI
apiVersion: v2
appVersion: 1.4.19
description: Chart for the DaemonSet DataKit
home: http://www.guance.com
icon: https://zhuyun-static-files-production.oss-cn-hangzhou.aliyuncs.com/images/datakit/datakit-icon-white-bg.png
keywords:
- Observable
maintainers:
- email: tanbiao@jiagouyun.com
  name: coanor
name: datakit
sources:
- https://github.com/GuanceCloud/datakit
type: application
version: 1.2.10
