apiVersion: v2
name: datakit
description: Chart for the DaemonSet Datakit
annotations:
  catalog.cattle.io/certified: partner # Enables the "partner" badge in the UI for easier identification
  catalog.cattle.io/release-name: datakit # Your chart's name in kebab-case, this is used for deployment
  catalog.cattle.io/display-name: Datakit # The chart's name you want displayed in the UI
type: application

appVersion: 1.4.19
version: 1.2.10

home: https://www.guance.com
icon: https://static.guance.com/images/datakit/datakit-icon-white-bg.png

keywords:
- Observability

maintainers:
- email: tanbiao@jiagouyun.com
  name: tanbiao

sources:
- https://github.com/GuanceCloud/datakit

dependencies:
- condition: kubeStateMetricsEnabled
  name: kube-state-metrics
  repository: file://./charts/kube-state-metrics
- condition: MetricsServerEnabled
  name: metrics-server
  repository: file://./charts/metrics-server
