
[[cms]]
  access_key_id = "AKIDXVFk7EfwUmzvc9mZR3TnqlTwZuyoJTxK"
  access_key_secret = "HH5f4PUJsBLFBrQjlY5TcXEuKTP7i5HG"

# ##See: https://cloud.tencent.com/document/product/213/6091
  region_id = "ap-shanghai"
  

  [[cms.namespace]]
    name='QCE/CVM'

#   ## Metrics to Pull (Required), See: https://cloud.tencent.com/document/api/248/30384
    [cms.namespace.metrics]
      names = [
        "CPUUsage",
      ]

#     ## dimensions can be used to query the specified resource, which is a collection of key-value forms. 
#     ## each metric may have its own dimensions, See: https://cloud.tencent.com/document/api/248/30384
#     ## name is metric name, value is json
      [[cms.namespace.metrics.dimensions]]
        name = "CPUUsage"
        value = '''
        [
            {"Dimensions":
              [
                { "Name": "InstanceId", "Value": "ins-9bpjauir" }
              ]
            }
        ]'''